# Generated by Django 6.0.1 on 2026-01-06 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTTPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='ott_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('release_date', models.DateField()),
                ('release_type', models.CharField(choices=[('THEATRE', 'Theatre'), ('OTT', 'OTT'), ('BOTH', 'Theatre + OTT')], max_length=10)),
                ('languages', models.CharField(help_text='Comma separated (Hindi, Tamil, Telugu)', max_length=200)),
                ('genres', models.CharField(help_text='Comma separated (Action, Drama)', max_length=200)),
                ('cast', models.TextField(help_text='Main cast names')),
                ('theatre_booking_link', models.URLField(blank=True)),
                ('ott_watch_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ott_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.ottplatform')),
            ],
        ),
    ]
