# Generated by Django 6.0.1 on 2026-01-11 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='poster'),
        ),
    ]
