# Generated by Django 6.0.1 on 2026-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 10 (e.g. 8.5)', max_digits=3, null=True),
        ),
    ]
