# Generated by Django 6.0.1 on 2026-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_poster_alter_ottplatform_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ottplatform',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
