# Generated by Django 6.0.1 on 2026-01-15 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_poster_alter_ottplatform_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synopsis_text', models.TextField()),
                ('predicted_rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='movies.movie')),
            ],
        ),
    ]
