# Generated by Django 6.0.1 on 2026-01-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_ratingprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='movies.movie')),
            ],
        ),
    ]
